name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_STORAGE_ACCOUNT_NAME: ${{ secrets.ARM_STORAGE_ACCOUNT_NAME }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP_NAME }}
      TF_VAR_gcloudProject: ${{ secrets.GCLOUD_PROJECT_ID }}
      TF_VAR_gcloudLocation: ${{ secrets.GCLOUD_LOCATION }}
      TF_VAR_serviceAccountKey: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      TF_VAR_clientId: ${{ secrets.GITHUB_CLIENT_ID }}
      TF_VAR_clientSecret: ${{ secrets.GITHUB_CLIENT_SECRET }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install Azure CLI
        uses: azure/cli@v1

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}

      - name: Run deploy script
        run: |
          chmod +x deploy.sh
          ./deploy.sh ${{ env.CONTAINER_NAME }} ${{ env.RESOURCE_GROUP }}